# Generated by Django 5.0 on 2024-11-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('botanical_name', models.CharField(blank=True, max_length=100, null=True)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('fruit_color', models.CharField(blank=True, max_length=100, null=True)),
                ('life_cycle', models.CharField(blank=True, max_length=100, null=True)),
                ('taste', models.CharField(blank=True, max_length=100, null=True)),
                ('germination_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('days_to_maturity', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=100, null=True)),
                ('sunlight_requirement', models.TextField(blank=True, null=True)),
                ('sowing', models.TextField(blank=True, null=True)),
                ('soil', models.TextField(blank=True, null=True)),
                ('watering', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.category')),
            ],
        ),
    ]
