# Generated by Django 5.0 on 2024-11-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_product_image_url_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tomato_plant_type',
            new_name='headerText',
        ),
    ]
