# Generated by Django 5.0 on 2024-11-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_headercarouselimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headercarouselimage',
            old_name='image',
            new_name='headerimage',
        ),
    ]
